/**
 * API route generator for the beehiiv CLI.
 * Generates Next.js App Router API routes for subscription management
 * including a subscribe endpoint and a subscription lookup/delete endpoint.
 * @module cli/generators/api-routes
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import Handlebars from 'handlebars';

/** Data required to generate the API routes */
export interface ApiRouteGeneratorData {
  /** The output directory to write the route files to */
  outputDir: string;
  /** The publication ID */
  publicationId: string;
}

/**
 * Inline Handlebars template for the subscription lookup/delete route.
 * This generates `app/api/beehiiv/subscription/[id]/route.ts` for
 * GET (get subscription by ID) and DELETE (unsubscribe).
 */
const SUBSCRIPTION_ID_ROUTE_TEMPLATE = `/**
 * Next.js App Router API route for beehiiv subscription lookup and management
 * Generated by \\\`beehiiv-react init\\\`
 * Located at: app/api/beehiiv/subscription/[id]/route.ts
 */
import { NextRequest, NextResponse } from 'next/server';
import { BeehiivClient } from 'beehiiv-react';
import { beehiivConfig } from '@/beehiiv.config';

/**
 * Initialize the beehiiv client using the server-side API key.
 * BEEHIIV_API_KEY must never be exposed to the client.
 */
const client = new BeehiivClient({
  apiKey: process.env.BEEHIIV_API_KEY!,
  publicationId: beehiivConfig.publicationId,
});

/** GET /api/beehiiv/subscription/[id] -- Get a subscription by ID */
export async function GET(
  _req: NextRequest,
  { params }: { params: { id: string } },
) {
  try {
    const subscription = await client.subscriptions.get(params.id);
    return NextResponse.json({ data: subscription }, { status: 200 });
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : 'Failed to fetch subscription';
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}

/** DELETE /api/beehiiv/subscription/[id] -- Unsubscribe */
export async function DELETE(
  _req: NextRequest,
  { params }: { params: { id: string } },
) {
  try {
    await client.subscriptions.delete(params.id);
    return NextResponse.json({ success: true }, { status: 200 });
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : 'Failed to unsubscribe';
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
`;

/**
 * Generate the Next.js API route files from Handlebars templates.
 *
 * Creates two route files:
 * 1. `{outputDir}/app/api/beehiiv/subscribe/route.ts` - POST endpoint for
 *    creating new subscriptions (from the `api-route.ts.hbs` template)
 * 2. `{outputDir}/app/api/beehiiv/subscription/[id]/route.ts` - GET and DELETE
 *    endpoints for subscription lookup and unsubscribe (from inline template)
 *
 * All necessary directories are created automatically.
 *
 * @param data - The output directory and publication ID configuration
 * @throws {Error} If the template file cannot be found or the output cannot be written
 *
 * @example
 * ```ts
 * await generateApiRoutes({
 *   outputDir: '.',
 *   publicationId: 'pub_abc123',
 * });
 * ```
 */
export async function generateApiRoutes(
  data: ApiRouteGeneratorData,
): Promise<void> {
  const { default: chalk } = await import('chalk');

  // Generate the subscribe route from template
  const templatePath = path.resolve(
    __dirname,
    '..',
    '..',
    '..',
    'templates',
    'api-route.ts.hbs',
  );

  const templateSource = fs.readFileSync(templatePath, 'utf-8');
  const template = Handlebars.compile(templateSource);
  const subscribeOutput = template({
    publicationId: data.publicationId,
  });

  const subscribePath = path.join(
    data.outputDir,
    'app',
    'api',
    'beehiiv',
    'subscribe',
    'route.ts',
  );
  fs.mkdirSync(path.dirname(subscribePath), { recursive: true });
  fs.writeFileSync(subscribePath, subscribeOutput, 'utf-8');
  console.log(chalk.green(`  Created ${subscribePath}`));

  // Generate the subscription/[id] route from inline template
  const subscriptionIdPath = path.join(
    data.outputDir,
    'app',
    'api',
    'beehiiv',
    'subscription',
    '[id]',
    'route.ts',
  );
  fs.mkdirSync(path.dirname(subscriptionIdPath), { recursive: true });
  fs.writeFileSync(subscriptionIdPath, SUBSCRIPTION_ID_ROUTE_TEMPLATE, 'utf-8');
  console.log(chalk.green(`  Created ${subscriptionIdPath}`));
}
