/**
 * API route generator for the beehiiv CLI.
 * Generates Next.js App Router API routes for subscription management
 * including a subscribe endpoint and a subscription lookup/delete endpoint.
 * @module cli/generators/api-routes
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import Handlebars from 'handlebars';
import { writeFileWithConfirm } from './utils.js';

/** Data required to generate the API routes */
export interface ApiRouteGeneratorData {
  /** The output directory to write the route files to */
  outputDir: string;
  /** The publication ID */
  publicationId: string;
}

/**
 * Inline Handlebars template for the subscription lookup/delete route.
 * This generates `app/api/beehiiv/subscription/[id]/route.ts` for
 * GET (get subscription by ID) and DELETE (unsubscribe).
 */
const SUBSCRIPTION_ID_ROUTE_TEMPLATE = `/**
 * Next.js App Router API route for beehiiv subscription lookup and management
 * Generated by \\\`beehiiv-react init\\\`
 * Located at: app/api/beehiiv/subscription/[id]/route.ts
 */
import { NextRequest, NextResponse } from 'next/server';
import { BeehiivClient } from 'beehiiv-react/server';
import beehiivConfig from '@/beehiiv.config';

/**
 * Initialize the beehiiv client using the server-side API key.
 * BEEHIIV_API_KEY must never be exposed to the client.
 */
const client = new BeehiivClient({
  apiKey: process.env.BEEHIIV_API_KEY!,
  publicationId: beehiivConfig.publicationId,
});

/** GET /api/beehiiv/subscription/[id] -- Get a subscription by ID */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { id } = await params;
    const subscription = await client.subscriptions.get(id);
    return NextResponse.json(subscription, { status: 200 });
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : 'Failed to fetch subscription';
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}

/** DELETE /api/beehiiv/subscription/[id] -- Unsubscribe */
export async function DELETE(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const { id } = await params;
    await client.subscriptions.delete(id);
    return NextResponse.json({ success: true }, { status: 200 });
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : 'Failed to unsubscribe';
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
`;

/**
 * Template-based route definitions for resources generated from .hbs files.
 * Each entry maps a template file name to its output directory path segment(s).
 */
const TEMPLATE_ROUTES: Array<{ template: string; outputPath: string[] }> = [
  { template: 'posts-route.ts.hbs', outputPath: ['posts'] },
  { template: 'authors-route.ts.hbs', outputPath: ['authors'] },
  { template: 'tiers-route.ts.hbs', outputPath: ['tiers'] },
  { template: 'engagements-route.ts.hbs', outputPath: ['engagements'] },
  { template: 'bulk-subscriptions-route.ts.hbs', outputPath: ['bulk-subscriptions'] },
];

/**
 * Generate the Next.js API route files from Handlebars templates.
 *
 * Creates route files for:
 * 1. `{outputDir}/app/api/beehiiv/subscribe/route.ts` - POST endpoint for
 *    creating new subscriptions (from the `api-route.ts.hbs` template)
 * 2. `{outputDir}/app/api/beehiiv/subscription/[id]/route.ts` - GET and DELETE
 *    endpoints for subscription lookup and unsubscribe (from inline template)
 * 3. `{outputDir}/app/api/beehiiv/posts/route.ts` - Posts list + detail
 * 4. `{outputDir}/app/api/beehiiv/authors/route.ts` - Authors list + detail
 * 5. `{outputDir}/app/api/beehiiv/tiers/route.ts` - Tiers list + detail
 * 6. `{outputDir}/app/api/beehiiv/engagements/route.ts` - Engagement metrics
 * 7. `{outputDir}/app/api/beehiiv/bulk-subscriptions/route.ts` - Bulk subscription creation
 *
 * All necessary directories are created automatically.
 *
 * @param data - The output directory and publication ID configuration
 * @throws {Error} If the template file cannot be found or the output cannot be written
 *
 * @example
 * ```ts
 * await generateApiRoutes({
 *   outputDir: '.',
 *   publicationId: 'pub_abc123',
 * });
 * ```
 */
export async function generateApiRoutes(
  data: ApiRouteGeneratorData,
): Promise<void> {
  // Generate the subscribe route from template
  const templatePath = path.resolve(
    __dirname,
    '..',
    '..',
    'templates',
    'api-route.ts.hbs',
  );

  const templateSource = fs.readFileSync(templatePath, 'utf-8');
  const template = Handlebars.compile(templateSource);
  const subscribeOutput = template({
    publicationId: data.publicationId,
  });

  const subscribePath = path.join(
    data.outputDir,
    'app',
    'api',
    'beehiiv',
    'subscribe',
    'route.ts',
  );
  await writeFileWithConfirm(subscribePath, subscribeOutput);

  // Generate the subscription/[id] route from inline template
  const subscriptionIdPath = path.join(
    data.outputDir,
    'app',
    'api',
    'beehiiv',
    'subscription',
    '[id]',
    'route.ts',
  );
  await writeFileWithConfirm(subscriptionIdPath, SUBSCRIPTION_ID_ROUTE_TEMPLATE);

  // Generate all template-based resource routes
  for (const route of TEMPLATE_ROUTES) {
    const routeTemplatePath = path.resolve(
      __dirname,
      '..',
      '..',
      'templates',
      route.template,
    );

    const routeTemplateSource = fs.readFileSync(routeTemplatePath, 'utf-8');
    const routeTemplate = Handlebars.compile(routeTemplateSource);
    const routeOutput = routeTemplate({
      publicationId: data.publicationId,
    });

    const routePath = path.join(
      data.outputDir,
      'app',
      'api',
      'beehiiv',
      ...route.outputPath,
      'route.ts',
    );
    await writeFileWithConfirm(routePath, routeOutput);
  }

}
